modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/The-Fireplace-Minecraft-Mods/Mob-Rebirth/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mob-rebirth"
credits=""
authors="The_Fireplace"

[[mods]]
modId="mobrebirth"
version="${file.jarVersion}"
displayName="Mob Rebirth"
description='''
A mod allowing mobs to be reborn in various ways.
'''

[[dependencies.mobrebirth]]
    modId="forge"
    mandatory=true
    versionRange="[28.1,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.mobrebirth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,)"
    ordering="NONE"
    side="SERVER"